### ISSUE TITLE
NPE when filtering list of events

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#183]
As reported on Google Play developer console

```java
java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getCount()' on a null object reference
at com.plusonelabs.calendar.calendar.CalendarEventProvider.queryList(CalendarEventProvider.java:130)
at com.plusonelabs.calendar.calendar.CalendarEventProvider.getTimeFilteredEventList(CalendarEventProvider.java:87)
at com.plusonelabs.calendar.calendar.CalendarEventProvider.getEvents(CalendarEventProvider.java:65)
at com.plusonelabs.calendar.calendar.CalendarEventVisualizer.getEventEntries(CalendarEventVisualizer.java:203)
at com.plusonelabs.calendar.EventRemoteViewsFactory.onDataSetChanged(EventRemoteViewsFactory.java:100)
at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.onDataSetChanged(RemoteViewsService.java:142)
at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:49)
at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by yvolk** [comment]
Fix pushed to repository. 
It's interesting, how many such crash reports you've got so far?

**Comment by mpost** [comment]
Currently there are 13 recorded crashes in the play console.

I have checked your fix. I wonder why the query would ever return `null` but the docs also state that this can happen.

**Comment by yvolk** [comment]
Yes, I looked up source code of another application: AndStatus, and I see that check for null cursor is present there also... so this really happens sometimes or on some devices...

**Comment by mpost** [comment]
:+1:

**Comment by mpost** [comment]
Closing this as resolved.

**Comment by mpost** [comment]
We have fixed the issue and are now starting to make use of the public beta testing channel. Please feel free to opt in and see if the fix works for you: https://play.google.com/apps/testing/com.plusonelabs.calendar (might take a bit until the link becomes active)
