### ISSUE TITLE
org.joda.time.IllegalInstantException when creating calendar event

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#186]
As reported in the Google Play Store. The issue has been existing in the 1.8.x release as well but continues to appear in 1.9.x.

```java
org.joda.time.IllegalInstantException: Illegal instant due to time zone offset transition (daylight savings time 'gap'): 1980-04-06T00:00:00.000 (Europe/Vienna)
at org.joda.time.DateTimeZone.convertLocalToUTC(DateTimeZone.java:997)
at com.plusonelabs.calendar.calendar.CalendarEventProvider.createCalendarEvent(CalendarEventProvider.java:250)
at com.plusonelabs.calendar.calendar.CalendarEventProvider.queryList(CalendarEventProvider.java:132)
at com.plusonelabs.calendar.calendar.CalendarEventProvider.getPastEventWithColorList(CalendarEventProvider.java:159)
at com.plusonelabs.calendar.calendar.CalendarEventProvider.getEvents(CalendarEventProvider.java:66)
at com.plusonelabs.calendar.calendar.CalendarEventVisualizer.getEventEntries(CalendarEventVisualizer.java:203)
at com.plusonelabs.calendar.EventRemoteViewsFactory.onDataSetChanged(EventRemoteViewsFactory.java:100)
at android.widget.RemoteViewsService$RemoteViewsFactoryAdapter.onDataSetChanged(RemoteViewsService.java:142)
at com.android.internal.widget.IRemoteViewsFactory$Stub.onTransact(IRemoteViewsFactory.java:49)
at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by yvolk** [comment]
As http://joda-time.sourceforge.net/faq.html#illegalinstant tells, this is expected behaviour of Joda library.
These are similar cases:
http://stackoverflow.com/questions/25233776/unable-to-create-a-specific-joda-datetime-illegalinstantexception
http://beust.com/weblog/2013/03/30/the-time-that-never-was/

Unfortunately, I couldn't reproduce this exception yet.

**Comment by yvolk** [comment]
And here is advice on how to handle  (and to reproduce?!) the problem:
http://stackoverflow.com/questions/5451152/how-to-handle-jodatime-illegal-instant-due-to-time-zone-offset-transition

**Comment by yvolk** [comment]
The bug is fixed and corresponding code cleaned. See com.plusonelabs.calendar.calendar.CalendarEventProvider#fixAllDayEvent

The test now passes: com.plusonelabs.calendar.WidgetEntriesTest#testIllegalInstantDueToTimeZoneOffsetTransition
