### ISSUE TITLE
Calendar crashes when you select an item. I use Android 7.1.1 

### ISSUE THREAD

**Issue by dharnidharvemuri** [plusonelabs/calendar-widget#277]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
	at com.android.calendar.event.EventInfoFragment.initAttendeesCursor(EventInfoFragment.java:803)
	at com.android.calendar.event.EventInfoFragment.access$3100(EventInfoFragment.java:109)
	at com.android.calendar.event.EventInfoFragment$QueryHandler.onQueryComplete(EventInfoFragment.java:489)
	at com.android.calendar.common.AsyncQueryService.handleMessage(AsyncQueryService.java:412)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Comment by dharnidharvemuri** [comment]
Any updates on the issue reported?

**Comment by yvolk** [comment]
I would say say that this looks like a firmware bug...

**Comment by dharnidharvemuri** [comment]
I do not think so. It seems to me more of a permission or access issue.
